/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  intro: [{ type: "autogenerated", dirName: "Intro" }],
  gear: [{ type: "autogenerated", dirName: "OctoGear" }],
  vault: [{ type: "autogenerated", dirName: "OctoVault" }],
  lend: [{ type: "autogenerated", dirName: "OctoLend" }],
  loop: [{ type: "autogenerated", dirName: "Loop" }],
  // Wrapped in an explicit category so the section landing page is served at
  // /docs/octopos rather than only existing as sidebar items.
  octopos: [
    {
      type: "category",
      label: "OctoPos",
      link: {
        type: "generated-index",
        slug: "/octopos",
        description:
          "Multi-chain DeFi intelligence — Stellar and EVM. Position tracking, risk monitoring, NAV oracle, and transaction building.",
      },
      items: [{ type: "autogenerated", dirName: "octopos" }],
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
