name: "Build and push to ECR"
on:
  push:
    branches:
      - main

env:
  AWS_REGION: europe-west2
  DOCKER_REGISTRY: europe-west2-docker.pkg.dev/untangled-v3/untangled-backend
  SERVICE_NAME: untangled-docs
  EKS_CLUSTER_NAME: eks-prod

jobs:
  prod:
    name: "Deploy app to prod env"
    runs-on: gke-16
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v2
      - name: Set env
        run: |
          echo "RELEASE_VERSION=prod-${{ github.run_id }}-${{ github.run_attempt }}" >> $GITHUB_ENV
          echo "ENV=prod" >> $GITHUB_ENV
          echo "NODE_SELECTOR=untangled-prod" >> $GITHUB_ENV
      - name: Build images
        run: ./deployment/build.sh $DOCKER_REGISTRY $AWS_REGION $SERVICE_NAME $RELEASE_VERSION
      - name: Deploy app
        run: |
          envsubst < deployment/app.yaml > deployment/a.yaml | kubectl apply -f deployment/a.yaml
          kubectl rollout status deploy/$SERVICE_NAME -n $ENV
      - name: Clean docker
        run: docker system prune -af
          
      