name: "Build and push to ECR"
on:
  push:
    branches:
      - main

env:
  AWS_REGION: eu-west-2
  DOCKER_REGISTRY: 470758053753.dkr.ecr.eu-west-2.amazonaws.com
  SERVICE_NAME: untangled-docs

jobs:
  prod:
    name: "Deploy app to prod env"
    runs-on: dev-runner
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v2
      - name: Set env
        run: |
          echo "RELEASE_VERSION=prod-${{ github.run_id }}-${{ github.run_attempt }}" >> $GITHUB_ENV
          echo "ENV=prod" >> $GITHUB_ENV
          echo "NODE_SELECTOR=untangled-prod" >> $GITHUB_ENV
      - name: ECR Login
        run: |
          echo $AWS_REGION 
          echo $DOCKER_REGISTRY 
          echo $RELEASE_VERSION
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $DOCKER_REGISTRY
      - name: Build images
        run: ./deployment/build.sh $DOCKER_REGISTRY $AWS_REGION $SERVICE_NAME $RELEASE_VERSION
      - name: Set config
        run: aws eks --region eu-west-2 update-kubeconfig --name dev-eks
      - name: Deploy app
        run: |
          envsubst < deployment/app.yaml > deployment/a.yaml | kubectl apply -f deployment/a.yaml
          kubectl rollout status deploy/$SERVICE_NAME -n $ENV
      - name: Clean docker
        run: docker system prune -af
          
      